namespace PokeGold.DataGen

open System.IO
open System.Text
open PokeGold.Game.Audio

/// Bakes the GSC songs and sound effects into F# literals, so the runtime never
/// parses `audio/music/*.asm` or `audio/sfx.asm`. Mirrors `EmitMaps`: the shared
/// `SongAsm` parser (in `PokeGold.MapData`) turns the `.asm` text into `Song`
/// values, and this module renders them as a `SongsData` module the game compiles.
module EmitSongs =

    let private str (s: string) : string =
        let e = s.Replace("\\", "\\\\").Replace("\"", "\\\"")
        "\"" + e + "\""

    let private boolLit (b: bool) : string = if b then "true" else "false"

    let private envLit (e: Envelope) : string =
        sprintf "{ Volume = %d; Sweep = %d }" e.Volume e.Sweep

    let private noiseLit (n: NoiseNote) : string =
        sprintf "{ Length = %d; Env = %s; Freq = %d }" n.Length (envLit n.Env) n.Freq

    let private envOptLit (o: Envelope option) : string =
        match o with
        | Some e -> sprintf "(Some %s)" (envLit e)
        | None -> "None"

    /// One SoundCommand rendered as its DU constructor literal.
    let private cmdLit (c: SoundCommand) : string =
        match c with
        | Note (p, l) -> sprintf "Note(%d, %d)" p l
        | Rest l -> sprintf "Rest %d" l
        | SquareNote (l, e, f) -> sprintf "SquareNote(%d, %s, %d)" l (envLit e) f
        | NoiseNoteCmd n -> sprintf "NoiseNoteCmd %s" (noiseLit n)
        | Octave o -> sprintf "Octave %d" o
        | NoteType (l, e) -> sprintf "NoteType(%d, %s)" l (envOptLit e)
        | Transpose (o, p) -> sprintf "Transpose(%d, %d)" o p
        | Tempo t -> sprintf "Tempo %d" t
        | TempoRelative t -> sprintf "TempoRelative %d" t
        | DutyCycle d -> sprintf "DutyCycle %d" d
        | DutyCyclePattern (a, b, c, d) -> sprintf "DutyCyclePattern(%d, %d, %d, %d)" a b c d
        | VolumeEnvelope e -> sprintf "VolumeEnvelope %s" (envLit e)
        | PitchSweep e -> sprintf "PitchSweep %s" (envLit e)
        | Vibrato (d, e, r) -> sprintf "Vibrato(%d, %d, %d)" d e r
        | PitchSlide (d, o, p) -> sprintf "PitchSlide(%d, %d, %d)" d o p
        | PitchOffset o -> sprintf "PitchOffset %d" o
        | Volume (l, r) -> sprintf "Volume(%d, %d)" l r
        | StereoPanning (l, r) -> sprintf "StereoPanning(%s, %s)" (boolLit l) (boolLit r)
        | ForceStereoPanning (l, r) -> sprintf "ForceStereoPanning(%s, %s)" (boolLit l) (boolLit r)
        | ToggleNoise k -> (match k with Some v -> sprintf "ToggleNoise(Some %d)" v | None -> "ToggleNoise None")
        | ToggleSfx -> "ToggleSfx"
        | SetCondition c -> sprintf "SetCondition %d" c
        | SoundCall t -> sprintf "SoundCall %d" t
        | SoundRet -> "SoundRet"
        | SoundLoop (n, t) -> sprintf "SoundLoop(%d, %d)" n t
        | SoundJump t -> sprintf "SoundJump %d" t
        | SoundJumpIf (c, t) -> sprintf "SoundJumpIf(%d, %d)" c t
        | NoOp -> "NoOp"

    let private commandsLit (cmds: SoundCommand[]) : string =
        cmds |> Array.map cmdLit |> String.concat "; "

    let private channelsLit (chans: (int * int)[]) : string =
        chans |> Array.map (fun (id, e) -> sprintf "(%d, %d)" id e) |> String.concat "; "

    /// The repo-relative paths of every music track file, with forward slashes
    /// (the exact keys the runtime uses to look songs up).
    let private musicPaths () : string list =
        let dir = Repo.path "audio/music"
        if Directory.Exists dir then
            Directory.GetFiles(dir, "*.asm")
            |> Array.map (fun f -> "audio/music/" + Path.GetFileName f)
            |> Array.sort
            |> Array.toList
        else []

    /// The full generated `Songs.Generated.fs` source.
    let render () : string =
        let sb = StringBuilder()
        sb.Append("// <auto-generated>\n") |> ignore
        sb.Append("//   Produced by PokeGold.DataGen from audio/music/*.asm and audio/sfx.asm.\n") |> ignore
        sb.Append("//   Do not edit by hand; regenerated on build. See engine-dotnet/tools/PokeGold.DataGen.\n") |> ignore
        sb.Append("// </auto-generated>\n\n") |> ignore
        sb.AppendLine("namespace PokeGold.Game.Data") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("open PokeGold.Game.Audio") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("/// Generated songs and sound effects, baked from the disassembly audio") |> ignore
        sb.AppendLine("/// scripts at build time. `byPath` keys music tracks by their repo-relative") |> ignore
        sb.AppendLine("/// file; `byName` keys SFX by their `Sfx_*` label.") |> ignore
        sb.AppendLine("module SongsData =") |> ignore
        sb.AppendLine() |> ignore

        // --- Music: one private command stream per track file. ---
        let mutable i = 0
        let musicEntries = ResizeArray<string * int>()
        for path in musicPaths () do
            match SongAsm.firstSong (Repo.readText path) with
            | Some song ->
                sb.AppendLine(sprintf "    let private mc_%d : SoundCommand[] = [| %s |]" i (commandsLit song.Commands)) |> ignore
                sb.AppendLine(sprintf "    let private mch_%d : (int * int)[] = [| %s |]" i (channelsLit song.Channels)) |> ignore
                musicEntries.Add(path, i)
                i <- i + 1
            | None -> ()

        sb.AppendLine() |> ignore

        // --- SFX: one shared command stream, sliced per `Sfx_*` header. ---
        let sfxSongs = SongAsm.allSongs (Repo.readText "audio/sfx.asm")
        match sfxSongs with
        | (_, first) :: _ ->
            sb.AppendLine(sprintf "    let private sfxCmds : SoundCommand[] = [| %s |]" (commandsLit first.Commands)) |> ignore
        | [] ->
            sb.AppendLine("    let private sfxCmds : SoundCommand[] = [| |]") |> ignore
        sb.AppendLine() |> ignore

        // --- Maps. ---
        sb.AppendLine("    /// Music tracks keyed by repo-relative `.asm` path.") |> ignore
        sb.AppendLine("    let byPath : Map<string, Song> =") |> ignore
        sb.AppendLine("        Map.ofArray [|") |> ignore
        for (path, idx) in musicEntries do
            sb.AppendLine(
                sprintf "            (%s, { ChannelCount = mch_%d.Length; Channels = mch_%d; Commands = mc_%d })"
                    (str path) idx idx idx)
            |> ignore
        sb.AppendLine("        |]") |> ignore
        sb.AppendLine() |> ignore

        sb.AppendLine("    /// Sound effects keyed by `Sfx_*` label; all share `sfxCmds`.") |> ignore
        sb.AppendLine("    let byName : Map<string, Song> =") |> ignore
        sb.AppendLine("        Map.ofArray [|") |> ignore
        for (name, song) in sfxSongs do
            sb.AppendLine(
                sprintf "            (%s, { ChannelCount = %d; Channels = [| %s |]; Commands = sfxCmds })"
                    (str name) song.ChannelCount (channelsLit song.Channels))
            |> ignore
        sb.AppendLine("        |]") |> ignore

        sb.ToString()
