namespace PokeGold.DataGen

open System.IO
open System.Text

/// Emits the parsed tables as F# source files containing plain literals. The
/// generated modules live in namespace `PokeGold.Game.Data` and reference the
/// `BaseStats` / `MoveData` records defined in the game's `Data/Schema.fs`.
module Emit =

    let private header =
        "// <auto-generated>\n\
         //   Produced by PokeGold.DataGen from the disassembly source tables.\n\
         //   Do not edit by hand; regenerated on build. See engine-dotnet/tools/PokeGold.DataGen.\n\
         // </auto-generated>\n"

    let private writeIfChanged (path: string) (content: string) =
        let changed =
            not (File.Exists path) || File.ReadAllText path <> content

        if changed then
            Directory.CreateDirectory(Path.GetDirectoryName path) |> ignore
            File.WriteAllText(path, content)

        changed

    let private typeChart () : string =
        let sb = StringBuilder()
        sb.Append(header).Append('\n') |> ignore
        sb.AppendLine("namespace PokeGold.Game.Data") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("/// Generated type ids and effectiveness matchups (multiplier x10).") |> ignore
        sb.AppendLine("module TypeChartData =") |> ignore
        sb.AppendLine() |> ignore

        sb.AppendLine("    let typeIds : Map<string, int> =") |> ignore
        sb.AppendLine("        Map.ofArray [|") |> ignore
        for name, id in Parsers.typeIds |> Map.toSeq |> Seq.sortBy snd do
            sb.AppendLine(sprintf "            (\"%s\", %d)" name id) |> ignore
        sb.AppendLine("        |]") |> ignore
        sb.AppendLine() |> ignore

        sb.AppendLine("    let matchups : Map<int * int, int> =") |> ignore
        sb.AppendLine("        Map.ofArray [|") |> ignore
        for (a, d), m in Parsers.typeMatchups do
            sb.AppendLine(sprintf "            ((%d, %d), %d)" a d m) |> ignore
        sb.AppendLine("        |]") |> ignore

        sb.ToString()

    let private speciesFile () : string =
        let sb = StringBuilder()
        sb.Append(header).Append('\n') |> ignore
        sb.AppendLine("namespace PokeGold.Game.Data") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("/// Generated base stats for every species, keyed by constant name.") |> ignore
        sb.AppendLine("module SpeciesData =") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("    let all : Map<string, BaseStats> =") |> ignore
        sb.AppendLine("        Map.ofArray [|") |> ignore

        for s in Parsers.species do
            sb.AppendLine(
                sprintf
                    "            (\"%s\", { Dex = %d; Name = \"%s\"; Hp = %d; Attack = %d; Defense = %d; Speed = %d; SpAttack = %d; SpDefense = %d; Type1 = %d; Type2 = %d; CatchRate = %d; BaseExp = %d; GrowthRate = %d })"
                    s.Constant s.Dex s.Constant s.Hp s.Attack s.Defense s.Speed s.SpAttack s.SpDefense s.Type1 s.Type2 s.CatchRate s.BaseExp s.GrowthRate
            )
            |> ignore

        sb.AppendLine("        |]") |> ignore
        sb.ToString()

    let private movesFile () : string =
        let sb = StringBuilder()
        sb.Append(header).Append('\n') |> ignore
        sb.AppendLine("namespace PokeGold.Game.Data") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("/// Generated move data, keyed by constant name.") |> ignore
        sb.AppendLine("module MovesData =") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("    let all : Map<string, MoveData> =") |> ignore
        sb.AppendLine("        Map.ofArray [|") |> ignore

        for mv in Parsers.moves do
            sb.AppendLine(
                sprintf
                    "            (\"%s\", { Name = \"%s\"; Effect = \"%s\"; Power = %d; Type = %d; Accuracy = %d; Pp = %d; EffectChance = %d })"
                    mv.Constant mv.Constant mv.Effect mv.Power mv.Type mv.Accuracy mv.Pp mv.EffectChance
            )
            |> ignore

        sb.AppendLine("        |]") |> ignore
        sb.AppendLine() |> ignore

        // 1-based index array: index 0 = placeholder (NO_MOVE), indices 1..N = GSC move constants.
        sb.AppendLine("    /// Move data in GSC declaration order. Index 0 is unused (NO_MOVE);") |> ignore
        sb.AppendLine("    /// index N corresponds to GSC move constant N (e.g. 1 = POUND).") |> ignore
        sb.AppendLine("    let byIndex : MoveData array =") |> ignore
        sb.AppendLine("        [|") |> ignore
        sb.AppendLine("            { Name = \"\"; Effect = \"\"; Power = 0; Type = 0; Accuracy = 0; Pp = 0; EffectChance = 0 } // 0 = NO_MOVE") |> ignore

        for mv in Parsers.moves do
            sb.AppendLine(
                sprintf
                    "            { Name = \"%s\"; Effect = \"%s\"; Power = %d; Type = %d; Accuracy = %d; Pp = %d; EffectChance = %d }"
                    mv.Constant mv.Effect mv.Power mv.Type mv.Accuracy mv.Pp mv.EffectChance
            )
            |> ignore

        sb.AppendLine("        |]") |> ignore
        sb.ToString()

    let private spriteMovementFile() : string =
        let sb = StringBuilder()
        sb.Append(header).Append('\n') |> ignore
        sb.AppendLine("namespace PokeGold.Game.Data") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("/// Generated `SPRITEMOVEDATA_*` rows: the movement function (`SPRITEMOVEFN_*`)") |> ignore
        sb.AppendLine("/// and initial facing for each, baked from data/sprites/map_objects.asm. Keyed") |> ignore
        sb.AppendLine("/// by the `SPRITEMOVEDATA_*` constant an object event names; the value is a") |> ignore
        sb.AppendLine("/// `(movementFn, facing)` pair the high-level NPC engine maps to behaviour.") |> ignore
        sb.AppendLine("module SpriteMovementData =") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("    let all : Map<string, string * string> =") |> ignore
        sb.AppendLine("        Map.ofArray [|") |> ignore

        for r in Parsers.spriteMovement do
            sb.AppendLine(sprintf "            (\"%s\", (\"%s\", \"%s\"))" r.Constant r.Fn r.Facing)
            |> ignore

        sb.AppendLine("        |]") |> ignore
        sb.ToString()

    let private musicFile () : string =
        let sb = StringBuilder()
        sb.Append(header).Append('\n') |> ignore
        sb.AppendLine("namespace PokeGold.Game.Data") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("/// Generated `MUSIC_*` song id -> repo-relative music `.asm` file, for every") |> ignore
        sb.AppendLine("/// song whose file ships in the tree. Built from the disassembly's parallel") |> ignore
        sb.AppendLine("/// music_constants / music_pointers tables.") |> ignore
        sb.AppendLine("module MusicData =") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("    let byId : Map<string, string> =") |> ignore
        sb.AppendLine("        Map.ofArray [|") |> ignore

        for (id, file) in MusicParsers.bindings () do
            sb.AppendLine(sprintf "            (\"%s\", \"%s\")" id file) |> ignore

        sb.AppendLine("        |]") |> ignore
        sb.ToString()

    let private escapeString (s: string) : string =
        s.Replace("\\", "\\\\").Replace("\"", "\\\"")

    let private itemsFile () : string =
        let sb = StringBuilder()
        sb.Append(header).Append('\n') |> ignore
        sb.AppendLine("namespace PokeGold.Game.Data") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("/// Generated item metadata, keyed by item constant name.") |> ignore
        sb.AppendLine("module ItemsData =") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("    let all : ItemData[] =") |> ignore
        sb.AppendLine("        [|") |> ignore

        for item in Parsers.items do
            let pocketCase =
                match item.Pocket with
                | "ITEM" -> "Item"
                | "BALL" -> "Ball"
                | "KEY_ITEM" -> "KeyItem"
                | "TM_HM" -> "TmHm"
                | _ -> "Item"
            
            sb.AppendLine(
                sprintf
                    "            { Id = \"%s\"; Name = \"%s\"; Price = %d; Pocket = %s; CantSelect = %s; CantToss = %s; HeldEffect = \"%s\"; Param = %d; FieldMenu = \"%s\"; BattleMenu = \"%s\"; Description = \"%s\" }"
                    item.Constant (escapeString item.DisplayName) item.Price pocketCase
                    (if item.CantSelect then "true" else "false")
                    (if item.CantToss then "true" else "false")
                    item.HeldEffect item.Param item.FieldMenu item.BattleMenu (escapeString item.Description)
            )
            |> ignore

        sb.AppendLine("        |]") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("    let byId : Map<string, ItemData> =") |> ignore
        sb.AppendLine("        all |> Array.map (fun d -> d.Id, d) |> Map.ofArray") |> ignore
        sb.ToString()

    let private martsFile () : string =
        let sb = StringBuilder()
        sb.Append(header).Append('\n') |> ignore
        sb.AppendLine("namespace PokeGold.Game.Data") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("/// Generated mart inventories, keyed by mart label name.") |> ignore
        sb.AppendLine("/// Source: data/items/marts.asm.") |> ignore
        sb.AppendLine("module MartsData =") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("    /// Item lists keyed by mart label (e.g. \"MartCherrygrove\").") |> ignore
        sb.AppendLine("    /// Values are ordered item constant strings matching ItemsData.byId keys.") |> ignore
        sb.AppendLine("    let byLabel : Map<string, string list> =") |> ignore
        sb.AppendLine("        Map.ofArray [|") |> ignore

        for mart in Parsers.marts do
            let items = mart.Items |> List.map (fun i -> sprintf "\"%s\"" i) |> String.concat "; "
            sb.AppendLine(sprintf "            (\"%s\", [ %s ])" mart.Label items) |> ignore

        sb.AppendLine("        |]") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("    /// Mart labels in the order they appear in the Marts: pointer table,") |> ignore
        sb.AppendLine("    /// corresponding to MART_* constants in constants/mart_constants.asm.") |> ignore
        sb.AppendLine("    let order : string list =") |> ignore
        sb.AppendLine("        [") |> ignore

        for label in Parsers.martOrder do
            sb.AppendLine(sprintf "            \"%s\"" label) |> ignore

        sb.AppendLine("        ]") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("    /// Item lists keyed by MART_* constant name (e.g. \"MART_AZALEA\" -> item list).") |> ignore
        sb.AppendLine("    /// Parallel to `order`: built by zipping MART_* enum names with `order`.") |> ignore
        sb.AppendLine("    let byConstant : Map<string, string list> =") |> ignore
        sb.AppendLine("        Map.ofArray [|") |> ignore

        let itemMap = Parsers.marts |> List.map (fun m -> m.Label, m.Items) |> Map.ofList
        for (constName, label) in List.zip Parsers.martConstantNames Parsers.martOrder do
            let items = itemMap |> Map.tryFind label |> Option.defaultValue []
            let itemStr = items |> List.map (fun i -> sprintf "\"%s\"" i) |> String.concat "; "
            sb.AppendLine(sprintf "            (\"%s\", [ %s ])" constName itemStr) |> ignore

        sb.AppendLine("        |]") |> ignore
        sb.ToString()

    let private trainersFile () : string =
        let sb = StringBuilder()
        sb.Append(header).Append('\n') |> ignore
        sb.AppendLine("namespace PokeGold.Game.Data") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("/// Generated trainer party data, keyed by group/id.") |> ignore
        sb.AppendLine("module TrainersData =") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("    let all : Map<string * int, TrainerData> =") |> ignore
        sb.AppendLine("        Map.ofList [") |> ignore

        for trainer in Parsers.trainers do
            let reward = Parsers.trainerRewards |> Map.tryFind trainer.Group |> Option.defaultValue 0
            let party =
                trainer.Party
                |> List.map (fun mon -> sprintf "            { Species = \"%s\"; Level = %d }" mon.Species mon.Level)
                |> String.concat ";\n"

            sb.AppendLine(sprintf "            ((\"%s\", %d), { Group = \"%s\"; Id = %d; Name = \"%s\"; Party = [" trainer.Group trainer.Id trainer.Group trainer.Id trainer.Name) |> ignore
            sb.AppendLine(party) |> ignore
            sb.AppendLine(sprintf "            ]; BaseReward = %d })" reward) |> ignore

        sb.AppendLine("        ]") |> ignore
        sb.ToString()

    let private evosAttacksFile () : string =
        let sb = StringBuilder()
        sb.Append(header).Append('\n') |> ignore
        sb.AppendLine("namespace PokeGold.Game.Data") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("/// Generated evolution and level-up learnset data, keyed by species constant name.") |> ignore
        sb.AppendLine("module EvosAttacksData =") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("    let all : Map<string, EvosAttacks> =") |> ignore
        sb.AppendLine("        Map.ofArray [|") |> ignore

        for entry in Parsers.evosAttacks do
            let evolutions =
                entry.Evolutions
                |> List.map (fun e -> sprintf "{ Method = \"%s\"; Param = \"%s\"; Param2 = \"%s\"; Target = \"%s\" }" e.Method e.Param e.Param2 e.Target)
                |> String.concat "; "

            let learnset =
                entry.Learnset
                |> List.map (fun l -> sprintf "{ Level = %d; Move = \"%s\" }" l.Level l.Move)
                |> String.concat "; "

            sb.AppendLine(sprintf "            (\"%s\", { Species = \"%s\"; Evolutions = [ %s ]; Learnset = [ %s ] })" entry.Species entry.Species evolutions learnset) |> ignore

        sb.AppendLine("        |]") |> ignore
        sb.ToString()

    let private dexFile () : string =
        let sb = StringBuilder()
        sb.Append(header).Append('\n') |> ignore
        sb.AppendLine("namespace PokeGold.Game.Data") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("/// Generated Pokédex entries for 251 species.") |> ignore
        sb.AppendLine("module DexData =") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("    let all : DexEntry[] =") |> ignore
        sb.AppendLine("        [|") |> ignore

        for entry in Parsers.dexEntries do
            match Parsers.species |> List.tryFind (fun s -> s.Constant = entry.Constant) with
            | Some species ->
                sb.AppendLine(
                    sprintf
                        "            { Num = %d; Name = \"%s\"; Category = \"%s\"; HeightDm = %d; WeightHg = %d; Description = \"%s\" }"
                        species.Dex entry.Constant (escapeString entry.Category) entry.HeightDm entry.WeightHg (escapeString entry.Description)
                )
                |> ignore
            | None -> ()  // Skip entries without matching species

        sb.AppendLine("        |]") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("    let byNum : Map<int, DexEntry> =") |> ignore
        sb.AppendLine("        all |> Array.map (fun d -> d.Num, d) |> Map.ofArray") |> ignore
        sb.ToString()

    /// Generate all data files into `outDir`. Returns the list of (path, changed).
    let all (outDir: string) : (string * bool) list =
        [ "TypeChart.Generated.fs", typeChart ()
          "Species.Generated.fs", speciesFile ()
          "Moves.Generated.fs", movesFile ()
          "EvosAttacks.Generated.fs", evosAttacksFile ()
          "SpriteMovement.Generated.fs", spriteMovementFile ()
          "Maps.Generated.fs", EmitMaps.render MapParsers.maps
          "StdScripts.Generated.fs", EmitMaps.renderStdScripts MapParsers.stdScripts MapParsers.stdText
          "Music.Generated.fs", musicFile ()
          "Songs.Generated.fs", EmitSongs.render ()
          "Items.Generated.fs", itemsFile ()
          "Marts.Generated.fs", martsFile ()
          "Trainers.Generated.fs", trainersFile ()
          "Dex.Generated.fs", dexFile () ]
        |> List.map (fun (name, content) ->
            let path = Path.Combine(outDir, name)
            path, writeIfChanged path content)
