namespace PokeGold.DataGen

open System.IO
open System.Text

/// Emits the parsed tables as F# source files containing plain literals. The
/// generated modules live in namespace `PokeGold.Game.Data` and reference the
/// `BaseStats` / `MoveData` records defined in the game's `Data/Schema.fs`.
module Emit =

    let private header =
        "// <auto-generated>\n\
         //   Produced by PokeGold.DataGen from the disassembly source tables.\n\
         //   Do not edit by hand; regenerated on build. See engine-dotnet/tools/PokeGold.DataGen.\n\
         // </auto-generated>\n"

    let private writeIfChanged (path: string) (content: string) =
        let changed =
            not (File.Exists path) || File.ReadAllText path <> content

        if changed then
            Directory.CreateDirectory(Path.GetDirectoryName path) |> ignore
            File.WriteAllText(path, content)

        changed

    let private typeChart () : string =
        let sb = StringBuilder()
        sb.Append(header).Append('\n') |> ignore
        sb.AppendLine("namespace PokeGold.Game.Data") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("/// Generated type ids and effectiveness matchups (multiplier x10).") |> ignore
        sb.AppendLine("module TypeChartData =") |> ignore
        sb.AppendLine() |> ignore

        sb.AppendLine("    let typeIds : Map<string, int> =") |> ignore
        sb.AppendLine("        Map.ofArray [|") |> ignore
        for name, id in Parsers.typeIds |> Map.toSeq |> Seq.sortBy snd do
            sb.AppendLine(sprintf "            (\"%s\", %d)" name id) |> ignore
        sb.AppendLine("        |]") |> ignore
        sb.AppendLine() |> ignore

        sb.AppendLine("    let matchups : Map<int * int, int> =") |> ignore
        sb.AppendLine("        Map.ofArray [|") |> ignore
        for (a, d), m in Parsers.typeMatchups do
            sb.AppendLine(sprintf "            ((%d, %d), %d)" a d m) |> ignore
        sb.AppendLine("        |]") |> ignore

        sb.ToString()

    let private speciesFile () : string =
        let sb = StringBuilder()
        sb.Append(header).Append('\n') |> ignore
        sb.AppendLine("namespace PokeGold.Game.Data") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("/// Generated base stats for every species, keyed by constant name.") |> ignore
        sb.AppendLine("module SpeciesData =") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("    let all : Map<string, BaseStats> =") |> ignore
        sb.AppendLine("        Map.ofArray [|") |> ignore

        for s in Parsers.species do
            sb.AppendLine(
                sprintf
                    "            (\"%s\", { Dex = %d; Name = \"%s\"; Hp = %d; Attack = %d; Defense = %d; Speed = %d; SpAttack = %d; SpDefense = %d; Type1 = %d; Type2 = %d })"
                    s.Constant s.Dex s.Constant s.Hp s.Attack s.Defense s.Speed s.SpAttack s.SpDefense s.Type1 s.Type2
            )
            |> ignore

        sb.AppendLine("        |]") |> ignore
        sb.ToString()

    let private movesFile () : string =
        let sb = StringBuilder()
        sb.Append(header).Append('\n') |> ignore
        sb.AppendLine("namespace PokeGold.Game.Data") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("/// Generated move data, keyed by constant name.") |> ignore
        sb.AppendLine("module MovesData =") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("    let all : Map<string, MoveData> =") |> ignore
        sb.AppendLine("        Map.ofArray [|") |> ignore

        for mv in Parsers.moves do
            sb.AppendLine(
                sprintf
                    "            (\"%s\", { Name = \"%s\"; Effect = \"%s\"; Power = %d; Type = %d; Accuracy = %d; Pp = %d; EffectChance = %d })"
                    mv.Constant mv.Constant mv.Effect mv.Power mv.Type mv.Accuracy mv.Pp mv.EffectChance
            )
            |> ignore

        sb.AppendLine("        |]") |> ignore
        sb.ToString()

    /// Generate all data files into `outDir`. Returns the list of (path, changed).
    let all (outDir: string) : (string * bool) list =
        [ "TypeChart.Generated.fs", typeChart ()
          "Species.Generated.fs", speciesFile ()
          "Moves.Generated.fs", movesFile () ]
        |> List.map (fun (name, content) ->
            let path = Path.Combine(outDir, name)
            path, writeIfChanged path content)
