<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PokeGold.Host</RootNamespace>
    <AssemblyName>PokeGold.Host</AssemblyName>
    <RollForward>Major</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="HostAudio.fs" />
    <Compile Include="HostGame.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.2.1105" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PokeGold.Game\PokeGold.Game.fsproj" />
  </ItemGroup>

</Project>
